# Generated by Django 4.0.5 on 2022-06-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='사용기술')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='developerStack',
            field=models.ManyToManyField(to='user.developerstack', verbose_name='사용기술'),
        ),
    ]
